### ISSUE TITLE
How to use view the nav pane in all tabs in netrw in vim

### ISSUE THREAD

**Issue by danedavid** [shapeshed/shapeshed.com#11]
I read your post on using `netrw` instead of NERDtree and found it very helpful. I just wanted to know how to keep the navigation pane in view if you are opening each new file in a new tab, that is, instead of this:

`let g:netrw_browse_split = 1`

if I use this:

`let g:netrw_browse_split = 3`

**Comment by shapeshed** [comment]
I don't think this is possible I'm afraid using tabs. You would have to go back to the tab with the directory view.
