### ISSUE TITLE
Trouble finding the PID

### ISSUE THREAD

**Issue by mesqueeb** [shapeshed/shapeshed.com#14]
Dear Shapeshed.
In your article on `ps`:
https://shapeshed.com/unix-ps/#how-to-just-get-the-process-id

you say the following:
> You can find the PID by doing:
> ps -ef | grep vim
> ```
> george   12608  5736  0 21:00 pts/2    00:00:11 vim content/post/unix-ps.md
> george   18324  5763  0 21:32 pts/3    00:00:00 grep vim
> ```

But you don't mention which number is the PID...

**Comment by shapeshed** [comment]
If you run `ps -ef | less ` you will see the column titles at the top

```
UID          PID    PPID  C STIME TTY          TIME CMD
```

So the PID is the second column. I will leave the artice as is but hope this helps. You have probably figured it out by now anyway!
