### ISSUE TITLE
Express not listening on localhost:3000

### ISSUE THREAD

**Issue by skbr1234** [shapeshed/shapeshed.com#3]
The booting code `DEBUG=express_example:* npm start` needs to be [updated](http://stackoverflow.com/q/40174157/2404470) to `DEBUG=express_example:* & npm start`

**Comment by shapeshed** [comment]
Are you on windows? The following should work if so.

``` bash
set DEBUG=express_example:* & npm start
```

**Comment by skbr1234** [comment]
Yes, on Windows. I would suggest you to update the code to cover that as well
