### ISSUE TITLE
unix-xargs. section "xargs vs exec" - note on command equivalence and performance

### ISSUE THREAD

**Issue by algor** [shapeshed/shapeshed.com#32]
The following statement seems erroneous.

> The following are equivalent.
> find ./foo -type f -name "*.txt" -exec rm {} \; 
> find ./foo -type f -name "*.txt" | xargs rm

The first command executes rm command for each file found by find separately (can count number of clone() system calls with strace util) while the xargs version as it is written (without specifying -n max-args) will do minimal number of invocations to use up the list of the files. Please see the excerpt from the xargs man page: 
> The command line for command is built up until it reaches a system-defined limit (unless the -n and -L options are used).  The specified command will be invoked as many times as
>        necessary to use up the list of input items.  In general, there will be many fewer invocations of command than there were items in the input.  This will normally  have  signifi‐
>        cant performance benefits. 

So it does not make sense to compare performance of these two commands as presented. 
You can use  -exec rm '{}' \+  to make find behave similarly. 
I have no idea of how performance compares in this case (going to try later), but can make a pretty good guess that the numbers should differ significantly.

**Comment by shapeshed** [comment]
I've updated the article with performance numbers. You are right that the difference in performance is substantial. 

```
touch {0..10000}.txt
time find ./ -type f -name "*.txt" -exec rm {} \;
find ./ -type f -name "*.txt" -exec rm {} \;  3.95s user 1.44s system 99% cpu 5.402 total
touch {0..10000}.txt
time find ./ -type f -name '*.txt' -delete
find ./ -type f -name '*.txt' -delete  0.03s user 0.06s system 98% cpu 0.090 total
```
