### ISSUE TITLE
Broken link, maybe invalid SSL

### ISSUE THREAD

**Issue by PickJBennett** [shapeshed/shapeshed.com#45]
On the page at https://shapeshed.com/default-styles-for-css/ the download link to https://cdn.shapeshed.com/downloads/default_css.zip is broken in Mobile Safari on iOS 13. The error message displayed reads:

“Safari cannot open the page because it could not establish a secure connection to the server.”

**Comment by shapeshed** [comment]
Thank you. This is a valid bug and I will resolve it.
