### ISSUE TITLE
Vim Native package

### ISSUE THREAD

**Issue by samzeng** [shapeshed/shapeshed.com#8]
I read the post you wrote about [Vim packages](https://shapeshed.com/vim-packages/), and I switch to native package too, but I found a strange question about `syntax` and `runtimepath`.

### Syntax error

![error](https://cloud.githubusercontent.com/assets/2367250/26588518/23cdfa94-4588-11e7-8b4e-77bcec749877.png)

### Syntax success
![success](https://cloud.githubusercontent.com/assets/2367250/26588554/40c1d1ca-4588-11e7-9100-80e6bc0e50e0.png)

The key is the order of both `syntax ebable` and `filetype plugin on`.

```
" Pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

" Nativa package
filetype plugin indent on
syntax on
```

Native package management and third-party package management in the runtimepath there is a certain difference.

**Comment by shapeshed** [comment]
Hey I think this one would be better answered by the [vim mailing list](https://groups.google.com/forum/#!forum/vim_use)
